print("Hello World!")
print("Hello again!")
print("I know this.")
print("Why am i doing this again?")
print("Well shiet nigguh")
print("Here we go again!")
print("The date today is 22 October 2022.")
print("We rebuild our skills once more.")
print("So we can have that office job we dreamed about, G.")
print("Fuck retail jobs!")
